// Auto-generated by tool/generate_profile.dart. Do not edit by hand.
//
// Documentation from Garmin's Profile.xlsx (github.com/garmin/fit-sdk-tools, release
// 21.214.0). Profile data is © Garmin under the FIT Protocol License.

import '../../profile.dart';

/// Release of garmin/fit-sdk-tools whose Profile.xlsx this documentation
/// comes from. It can predate the profile: Garmin does not tag
/// fit-sdk-tools for every profile release.
const String profileDocsVersion = '21.214.0';

/// Section of Profile.xlsx each message is listed under (e.g.
/// `ACTIVITY FILE MESSAGES`), by global message number.
const Map<int, String> profileMessageSections = {
  1: 'DEVICE FILE MESSAGES',
  2: 'SETTINGS FILE MESSAGES',
  3: 'SETTINGS FILE MESSAGES',
  4: 'SETTINGS FILE MESSAGES',
  5: 'SETTINGS FILE MESSAGES',
  6: 'SETTINGS FILE MESSAGES',
  7: 'SPORT SETTINGS FILE MESSAGES',
  8: 'SPORT SETTINGS FILE MESSAGES',
  9: 'SPORT SETTINGS FILE MESSAGES',
  10: 'SPORT SETTINGS FILE MESSAGES',
  12: 'SPORT SETTINGS FILE MESSAGES',
  13: 'SPORT SETTINGS FILE MESSAGES',
  15: 'GOALS FILE MESSAGES',
  18: 'ACTIVITY FILE MESSAGES',
  19: 'ACTIVITY FILE MESSAGES',
  20: 'ACTIVITY FILE MESSAGES',
  21: 'ACTIVITY FILE MESSAGES',
  23: 'ACTIVITY FILE MESSAGES',
  26: 'WORKOUT FILE MESSAGES',
  27: 'WORKOUT FILE MESSAGES',
  28: 'SCHEDULE FILE MESSAGES',
  30: 'WEIGHT SCALE FILE MESSAGES',
  31: 'COURSE FILE MESSAGES',
  32: 'COURSE FILE MESSAGES',
  33: 'TOTALS FILE MESSAGES',
  34: 'ACTIVITY FILE MESSAGES',
  35: 'DEVICE FILE MESSAGES',
  37: 'DEVICE FILE MESSAGES',
  38: 'DEVICE FILE MESSAGES',
  39: 'DEVICE FILE MESSAGES',
  51: 'BLOOD PRESSURE FILE MESSAGES',
  53: 'SPORT SETTINGS FILE MESSAGES',
  55: 'MONITORING FILE MESSAGES',
  72: 'ACTIVITY FILE MESSAGES',
  78: 'OTHER MESSAGES',
  80: 'OTHER MESSAGES',
  81: 'OTHER MESSAGES',
  82: 'OTHER MESSAGES',
  101: 'ACTIVITY FILE MESSAGES',
  103: 'MONITORING FILE MESSAGES',
  106: 'DEVICE FILE MESSAGES',
  127: 'SETTINGS FILE MESSAGES',
  128: 'ACTIVITY FILE MESSAGES',
  129: 'ACTIVITY FILE MESSAGES',
  131: 'SPORT SETTINGS FILE MESSAGES',
  132: 'MONITORING FILE MESSAGES',
  142: 'SEGMENT FILE MESSAGES',
  145: 'OTHER MESSAGES',
  148: 'SEGMENT FILE MESSAGES',
  149: 'SEGMENT FILE MESSAGES',
  150: 'SEGMENT FILE MESSAGES',
  151: 'SEGMENT LIST FILE MESSAGES',
  158: 'WORKOUT FILE MESSAGES',
  159: 'SETTINGS FILE MESSAGES',
  160: 'ACTIVITY FILE MESSAGES',
  161: 'ACTIVITY FILE MESSAGES',
  164: 'ACTIVITY FILE MESSAGES',
  165: 'ACTIVITY FILE MESSAGES',
  167: 'ACTIVITY FILE MESSAGES',
  169: 'ACTIVITY FILE MESSAGES',
  174: 'ACTIVITY FILE MESSAGES',
  177: 'ACTIVITY FILE MESSAGES',
  178: 'ACTIVITY FILE MESSAGES',
  184: 'ACTIVITY FILE MESSAGES',
  185: 'ACTIVITY FILE MESSAGES',
  186: 'ACTIVITY FILE MESSAGES',
  187: 'ACTIVITY FILE MESSAGES',
  188: 'SETTINGS FILE MESSAGES',
  200: 'OTHER MESSAGES',
  201: 'OTHER MESSAGES',
  202: 'OTHER MESSAGES',
  206: 'ACTIVITY FILE MESSAGES',
  207: 'ACTIVITY FILE MESSAGES',
  208: 'ACTIVITY FILE MESSAGES',
  209: 'ACTIVITY FILE MESSAGES',
  210: 'ACTIVITY FILE MESSAGES',
  211: 'MONITORING FILE MESSAGES',
  216: 'SETTINGS FILE MESSAGES',
  225: 'ACTIVITY FILE MESSAGES',
  227: 'MONITORING FILE MESSAGES',
  229: 'MONITORING FILE MESSAGES',
  258: 'SPORT SETTINGS FILE MESSAGES',
  259: 'SPORT SETTINGS FILE MESSAGES',
  262: 'SPORT SETTINGS FILE MESSAGES',
  264: 'WORKOUT FILE MESSAGES',
  268: 'OTHER MESSAGES',
  269: 'MONITORING FILE MESSAGES',
  275: 'OTHER MESSAGES',
  285: 'ACTIVITY FILE MESSAGES',
  289: 'OTHER MESSAGES',
  290: 'OTHER MESSAGES',
  297: 'OTHER MESSAGES',
  302: 'MONITORING FILE MESSAGES',
  304: 'MONITORING FILE MESSAGES',
  305: 'MONITORING FILE MESSAGES',
  306: 'MONITORING FILE MESSAGES',
  307: 'MONITORING FILE MESSAGES',
  308: 'MONITORING FILE MESSAGES',
  312: 'ACTIVITY FILE MESSAGES',
  313: 'ACTIVITY FILE MESSAGES',
  314: 'MONITORING FILE MESSAGES',
  315: 'MONITORING FILE MESSAGES',
  317: 'ACTIVITY FILE MESSAGES',
  319: 'OTHER MESSAGES',
  323: 'OTHER MESSAGES',
  346: 'OTHER MESSAGES',
  370: 'OTHER MESSAGES',
  371: 'OTHER MESSAGES',
  372: 'OTHER MESSAGES',
  375: 'ACTIVITY FILE MESSAGES',
  376: 'MONITORING FILE MESSAGES',
  387: 'OTHER MESSAGES',
  388: 'OTHER MESSAGES',
  389: 'MONITORING FILE MESSAGES',
  393: 'SPORT SETTINGS FILE MESSAGES',
  398: 'OTHER MESSAGES',
  409: 'MONITORING FILE MESSAGES',
  412: 'OTHER MESSAGES',
  470: 'OTHER MESSAGES',
  471: 'OTHER MESSAGES',
};

/// Comment on each documented message, by global message number.
const Map<int, String> profileMessageDocs = {
  0: 'Must be first message in file.',
  72: 'Corresponds to file_id of workout or course.',
  78: 'Heart rate variability',
  148: 'Unique Identification data for a segment file',
  149:
      'Unique Identification data for an individual segment leader within a segment file',
  150:
      'Navigation and race evaluation point for a segment decribing a point along the segment path and time it took each segment leader to reach that point',
  151:
      'Summary of the unique segment and leaderboard information associated with a segment file. This message is used to compile a segment list file describing all segment files on a device. The segment list file is used when refreshing the contents of a segment file with the latest available leaderboard information.',
  206: 'Must be logged before developer field is used',
  207: 'Must be logged before field description',
  227: 'Value from 1 to 100 calculated by FirstBeat',
  289:
      'Number of acclerometer zero crossings summed over the specified time interval',
  290: 'Array of heart beat intervals',
  302: 'Raw accelerometer data used for HSA custom data logging',
  304: 'User\'s current daily step data used for HSA custom data logging',
  305: 'User\'s current SpO2 data used for HSA custom data logging',
  306: 'User\'s current stress data used for HSA custom data logging',
  307: 'User\'s current respiration data used for HSA custom data logging',
  308: 'User\'s current heart rate data used for HSA custom data logging',
  314: 'Body battery data used for HSA custom data logging',
  315: 'HSA events',
  372: 'Raw Beat-to-Beat Interval values',
  387: 'Specifically used for XERO products.',
  388: 'Specifically used for XERO products.',
  389: 'Configuration data for HSA custom data logging',
  409: 'Wrist temperature data used for HSA custom data logging',
};

/// Comment on each documented field, by message number then field
/// number.
const Map<int, Map<int, String>> profileFieldDocs = {
  0: {
    4: 'Only set for files that are can be created/erased.',
    5: 'Only set for files that are not created/erased.',
    8: 'Optional free form string to indicate the devices name or model',
  },
  1: {
    0: 'Use language_bits_x types where x is index of array.',
    1: 'Use sport_bits_x types where x is index of array.',
  },
  2: {
    0: 'Index into time zone arrays.',
    1: 'Offset from system time. Required to convert timestamp from system time to UTC.',
    2: 'Offset from system time.',
    4: 'Display mode for the time',
    5: 'timezone offset in 1/4 hour increments',
    12: 'Mode for backlight',
    36: 'Enabled state of the activity tracker functionality',
    39: 'UTC timestamp used to set the devices clock and date',
    40: 'Bitfield to configure enabled screens for each supported loop',
    46: 'Enabled state of the move alert',
    47: 'Display mode for the date',
    57: 'Bitfield to indicate one page as default for each supported loop',
    58: 'Minimum steps before an autosync can occur',
    59: 'Minimum minutes before an autosync can occur',
    80: 'Enable auto-detect setting for the lactate threshold feature.',
    86: 'Automatically upload using BLE',
    89: 'Helps to conserve battery by changing modes',
    90: 'Allows setting specific activities auto-activity detect enabled/disabled settings',
    94: 'Number of screens configured to display',
    95: 'Smart Notification display orientation',
    174: 'Used to hold the tap threshold setting',
  },
  3: {
    0: 'Used for Morning Report greeting',
    28: 'Typical wake time',
    29: 'Typical bed time',
    31: 'User defined running step length set to 0 for auto length',
    32: 'User defined walking step length set to 0 for auto length',
  },
  5: {
    4: 'Use footpod for speed source instead of GPS',
    7: 'Rollover counter that can be used to extend the odometer',
  },
  6: {
    37: 'Rollover counter that can be used to extend the odometer',
    38: 'Number of front gears',
    39: 'Number of teeth on each gear 0 is innermost',
    40: 'Number of rear gears',
    41: 'Number of teeth on each gear 0 is innermost',
  },
  13: {
    153: 'A more precise target speed field',
  },
  18: {
    0: 'session',
    1: 'stop',
    7: 'Time (includes pauses)',
    8: 'Timer Time (excludes pauses)',
    14: 'total_distance / total_timer_time',
    16: 'average heart rate (excludes pause time)',
    18: 'total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time',
    20: 'total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time',
    29: 'North east corner latitude',
    30: 'North east corner longitude',
    31: 'South west corner latitude',
    32: 'South west corner longitude',
    33: '# of lengths of swim pool',
    47: '# of active lengths of swim pool',
    85: 'stroke_type enum used as the index',
    86: 'zone number used as the index',
    92: 'fractional part of the avg_cadence',
    93: 'fractional part of the max_cadence',
    94: 'fractional part of the total_cycles',
    95: 'Avg saturated and unsaturated hemoglobin',
    96: 'Min saturated and unsaturated hemoglobin',
    97: 'Max saturated and unsaturated hemoglobin',
    98: 'Avg percentage of hemoglobin saturated with oxygen',
    99: 'Min percentage of hemoglobin saturated with oxygen',
    100: 'Max percentage of hemoglobin saturated with oxygen',
    110: 'Sport name from associated sport mesg',
    112: 'Total time spend in the standing position',
    113: 'Number of transitions to the standing state',
    114: 'Average platform center offset Left',
    115: 'Average platform center offset Right',
    116:
        'Average left power phase angles. Indexes defined by power_phase_type.',
    117:
        'Average left power phase peak angles. Data value indexes defined by power_phase_type.',
    118:
        'Average right power phase angles. Data value indexes defined by power_phase_type.',
    119:
        'Average right power phase peak angles data value indexes defined by power_phase_type.',
    120:
        'Average power by position. Data value indexes defined by rider_position_type.',
    121:
        'Maximum power by position. Data value indexes defined by rider_position_type.',
    122:
        'Average cadence by position. Data value indexes defined by rider_position_type.',
    123:
        'Maximum cadence by position. Data value indexes defined by rider_position_type.',
    124: 'total_distance / total_timer_time',
    129: 'lev average motor power during session',
    130: 'lev maximum motor power during session',
    131: 'lev battery consumption during session',
    140: '0 if above water',
    141: '0 if above water',
    142: 'Time since end of last dive',
    181:
        'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    182:
        'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    186:
        'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    187:
        'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    192:
        'A 0-100 scale representing how a user felt while performing a workout. Low values are considered feeling bad, while high values are good.',
    193:
        'Common Borg CR10 / 0-10 RPE scale, multiplied 10x.. Aggregate score for all workouts in a single session.',
    194: 'Average SPO2 for the monitoring session',
    195: 'Average stress for the monitoring session',
    197:
        'Standard deviation of R-R interval (SDRR) - Heart rate variability measure most useful for wellness users.',
    198:
        'Root mean square successive difference (RMSSD) - Heart rate variability measure most useful for athletes',
    199: 'fractional part of total_ascent',
    200: 'fractional part of total_descent',
    254: 'Selected bit is set for the current session.',
  },
  19: {
    7: 'Time (includes pauses)',
    8: 'Timer Time (excludes pauses)',
    12: 'If New Leaf',
    17: 'total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time',
    19: 'total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time',
    32: '# of lengths of swim pool',
    40: '# of active lengths of swim pool',
    75: 'stroke_type enum used as the index',
    76: 'zone number used as the index',
    80: 'fractional part of the avg_cadence',
    81: 'fractional part of the max_cadence',
    82: 'fractional part of the total_cycles',
    84: 'Avg saturated and unsaturated hemoglobin',
    85: 'Min saturated and unsaturated hemoglobin',
    86: 'Max saturated and unsaturated hemoglobin',
    87: 'Avg percentage of hemoglobin saturated with oxygen',
    88: 'Min percentage of hemoglobin saturated with oxygen',
    89: 'Max percentage of hemoglobin saturated with oxygen',
    98: 'Total time spent in the standing position',
    99: 'Number of transitions to the standing state',
    100: 'Average left platform center offset',
    101: 'Average right platform center offset',
    102:
        'Average left power phase angles. Data value indexes defined by power_phase_type.',
    103:
        'Average left power phase peak angles. Data value indexes defined by power_phase_type.',
    104:
        'Average right power phase angles. Data value indexes defined by power_phase_type.',
    105:
        'Average right power phase peak angles. Data value indexes defined by power_phase_type.',
    106:
        'Average power by position. Data value indexes defined by rider_position_type.',
    107:
        'Maximum power by position. Data value indexes defined by rider_position_type.',
    108:
        'Average cadence by position. Data value indexes defined by rider_position_type.',
    109:
        'Maximum cadence by position. Data value indexes defined by rider_position_type.',
    115: 'lev average motor power during lap',
    116: 'lev maximum motor power during lap',
    117: 'lev battery consumption during lap',
    122: '0 if above water',
    123: '0 if above water',
    149:
        'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    150:
        'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    153:
        'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    154:
        'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    156: 'fractional part of total_ascent',
    157: 'fractional part of total_descent',
  },
  20: {
    10: 'Relative. 0 is none 254 is Max.',
    17: 'Speed at 1s intervals. Timestamp field indicates time of last array element.',
    52: 'Log cadence and fractional cadence for backwards compatability',
    54: 'Total saturated and unsaturated hemoglobin',
    55: 'Min saturated and unsaturated hemoglobin',
    56: 'Max saturated and unsaturated hemoglobin',
    57: 'Percentage of hemoglobin saturated with oxygen',
    58: 'Min percentage of hemoglobin saturated with oxygen',
    59: 'Max percentage of hemoglobin saturated with oxygen',
    67: 'Left platform center offset',
    68: 'Right platform center offset',
    69: 'Left power phase angles. Data value indexes defined by power_phase_type.',
    70: 'Left power phase peak angles. Data value indexes defined by power_phase_type.',
    71: 'Right power phase angles. Data value indexes defined by power_phase_type.',
    72: 'Right power phase peak angles. Data value indexes defined by power_phase_type.',
    81: 'lev battery state of charge',
    82: 'lev motor power',
    87: 'Supports larger cycle sizes needed for paddlesports. Max cycle size: 655.35',
    91: 'Includes atmospheric pressure',
    92: '0 if above water',
    93: '0 if above water',
    114:
        'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    115:
        'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    116: 'Current Stress value',
    124: 'Pressure-based surface air consumption',
    125: 'Volumetric surface air consumption',
    126: 'Respiratory minute volume',
    129: 'Current partial pressure of oxygen',
  },
  21: {
    7: 'Do not populate directly. Autogenerated by decoder for sport_point subfield components',
    8: 'Do not populate directly. Autogenerated by decoder for sport_point subfield components',
    9: 'Do not populate directly. Autogenerated by decoder for gear_change subfield components. Front gear number. 1 is innermost.',
    10: 'Do not populate directly. Autogenerated by decoder for gear_change subfield components. Number of front teeth.',
    11: 'Do not populate directly. Autogenerated by decoder for gear_change subfield components. Rear gear number. 1 is innermost.',
    12: 'Do not populate directly. Autogenerated by decoder for gear_change subfield components. Number of rear teeth.',
    14: 'Activity Type associated with an auto_activity_detect event',
    15: 'Timestamp of when the event started',
    21: 'Do not populate directly. Autogenerated by decoder for threat_alert subfield components.',
    22: 'Do not populate directly. Autogenerated by decoder for threat_alert subfield components.',
    23: 'Do not populate directly. Autogenerated by decoder for radar_threat_alert subfield components',
    24: 'Do not populate directly. Autogenerated by decoder for radar_threat_alert subfield components',
  },
  23: {
    7: 'Reset by new battery or charge.',
    18: 'Indicates the location of the sensor',
    19: 'Used to describe the sensor or location',
    27: 'Optional free form string to indicate the devices name or model',
  },
  26: {
    6: 'number of valid steps',
    17: 'Description of the workout',
  },
  28: {
    0: 'Corresponds to file_id of scheduled workout / course.',
    1: 'Corresponds to file_id of scheduled workout / course.',
    2: 'Corresponds to file_id of scheduled workout / course.',
    3: 'Corresponds to file_id of scheduled workout / course.',
    4: 'TRUE if this activity has been started',
  },
  30: {
    9: '~4kJ per kcal, 0.25 allows max 16384 kcal',
    12: 'Associates this weight scale message to a user. This corresponds to the index of the user profile message in the weight scale file.',
  },
  33: {
    0: 'Excludes pauses',
    4: 'Includes pauses',
  },
  34: {
    0: 'Exclude pauses',
    5: 'timestamp epoch expressed in local time, used to convert activity timestamps to local time',
  },
  51: {
    9: 'Associates this blood pressure message to a user. This corresponds to the index of the user profile message in the blood pressure file.',
  },
  55: {
    0: 'Associates this data to device_info message. Not required for file with single device (sensor).',
    1: 'Accumulated total calories. Maintained by MonitoringReader for each activity_type. See SDK documentation',
    2: 'Accumulated distance. Maintained by MonitoringReader for each activity_type. See SDK documentation.',
    3: 'Accumulated cycles. Maintained by MonitoringReader for each activity_type. See SDK documentation.',
    11: 'Must align to logging interval, for example, time must be 00:00:00 for daily log.',
    12: 'Avg temperature during the logging interval ended at timestamp',
    14: 'Min temperature during the logging interval ended at timestamp',
    15: 'Max temperature during the logging interval ended at timestamp',
    16: 'Indexed using minute_activity_level enum',
    24: 'Indicates single type / intensity for duration since last monitoring message.',
    41: 'Wheelchair Pushes',
    253:
        'Must align to logging interval, for example, time must be 00:00:00 for daily log.',
  },
  78: {
    0: 'Time between beats',
  },
  101: {
    20: 'stroke_type enum used as the index',
    21: 'zone number used as the index',
  },
  103: {
    0: 'Use to convert activity timestamps to local time if device does not support time zone and daylight savings time correction.',
    3: 'Indexed by activity_type',
    4: 'Indexed by activity_type',
  },
  127: {
    0: 'Use Bluetooth for connectivity features',
    1: 'Use Bluetooth Low Energy for connectivity features',
    2: 'Use ANT for connectivity features',
  },
  128: {
    0: 'Current or forecast',
    2: 'Corresponds to GSC Response weatherIcon field',
    5: 'range 0-100',
    6: 'Heat Index if GCS heatIdx above or equal to 90F or wind chill if GCS windChill below or equal to 32F',
    8: 'string corresponding to GCS response location string',
    253: 'time of update for current conditions, else forecast time',
  },
  129: {
    0: 'Unique identifier from GCS report ID string, length is 12',
    1: 'Time alert was issued',
    2: 'Time alert expires',
    3: 'Warning, Watch, Advisory, Statement',
    4: 'Tornado, Severe Thunderstorm, etc.',
  },
  142: {
    7: 'Time (includes pauses)',
    8: 'Timer Time (excludes pauses)',
    12: 'If New Leaf',
    17: 'total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time',
    19: 'total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time',
    25: 'North east corner latitude.',
    26: 'North east corner longitude.',
    27: 'South west corner latitude.',
    28: 'South west corner latitude.',
    66: 'fractional part of the avg_cadence',
    67: 'fractional part of the max_cadence',
    68: 'fractional part of the total_cycles',
    71: 'Total time spent in the standing position',
    72: 'Number of transitions to the standing state',
    73: 'Average left platform center offset',
    74: 'Average right platform center offset',
    75: 'Average left power phase angles. Data value indexes defined by power_phase_type.',
    76: 'Average left power phase peak angles. Data value indexes defined by power_phase_type.',
    77: 'Average right power phase angles. Data value indexes defined by power_phase_type.',
    78: 'Average right power phase peak angles. Data value indexes defined by power_phase_type.',
    79: 'Average power by position. Data value indexes defined by rider_position_type.',
    80: 'Maximum power by position. Data value indexes defined by rider_position_type.',
    81: 'Average cadence by position. Data value indexes defined by rider_position_type.',
    82: 'Maximum cadence by position. Data value indexes defined by rider_position_type.',
    83: 'Manufacturer that produced the segment',
    84: 'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    85: 'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    86: 'The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.',
    87: 'The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.',
    89: 'fractional part of total_ascent',
    90: 'fractional part of total_descent',
  },
  145: {
    0: 'Deprecated. Use data field.',
    1: 'Message Number of the parent message',
    2: 'Index of mesg that this glob is associated with.',
    3: 'Field within the parent that this glob is associated with',
    4: 'Block of utf8 bytes. Note, mutltibyte characters may be split across adjoining memo_glob messages.',
    250: 'Sequence number of memo blocks',
  },
  148: {
    0: 'Friendly name assigned to segment',
    1: 'UUID of the segment',
    2: 'Sport associated with the segment',
    3: 'Segment enabled for evaluation',
    4: 'Primary key of the user that created the segment',
    5: 'ID of the device that created the segment',
    6: 'Index for the Leader Board entry selected as the default race participant',
    7: 'Indicates if any segments should be deleted',
    8: 'Indicates how the segment was selected to be sent to the device',
  },
  149: {
    0: 'Friendly name assigned to leader',
    1: 'Leader classification',
    2: 'Primary user ID of this leader',
    3: 'ID of the activity associated with this leader time',
    4: 'Segment Time (includes pauses)',
    5: 'String version of the activity_id. 21 characters long, express in decimal',
  },
  150: {
    3: 'Accumulated distance along the segment at the described point',
    4: 'Accumulated altitude along the segment at the described point',
    5: 'Accumualted time each leader board member required to reach the described point. This value is zero for all leader board members at the starting point of the segment.',
    6: 'Accumulated altitude along the segment at the described point',
  },
  151: {
    1: 'UUID of the segment file',
    3: 'Enabled state of the segment file',
    4: 'Primary key of the user that created the segment file',
    7: 'Leader type of each leader in the segment file',
    8: 'Group primary key of each leader in the segment file',
    9: 'Activity ID of each leader in the segment file',
    10: 'String version of the activity ID of each leader in the segment file. 21 characters long for each ID, express in decimal',
    11: 'Index for the Leader Board entry selected as the default race participant',
  },
  160: {
    0: 'Millisecond part of the timestamp.',
    6: 'Used to correlate UTC to system time if the timestamp of the message is in system time. This UTC time is derived from the GPS data.',
    7: 'velocity[0] is lon velocity. Velocity[1] is lat velocity. Velocity[2] is altitude velocity.',
    253: 'Whole second part of the timestamp.',
  },
  161: {
    0: 'Millisecond part of the timestamp.',
    253: 'Whole second part of the timestamp.',
  },
  162: {
    0: 'Fractional part of the UTC timestamp at the time the system timestamp was recorded.',
    1: 'Whole second part of the system timestamp',
    2: 'Fractional part of the system timestamp',
    3: 'timestamp epoch expressed in local time used to convert timestamps to local time',
    4: 'Millisecond part of the UTC timestamp at the time the system timestamp was recorded.',
    5: 'Millisecond part of the system timestamp',
    253:
        'Whole second part of UTC timestamp at the time the system timestamp was recorded.',
  },
  164: {
    0: 'Millisecond part of the timestamp.',
    1: 'Each time in the array describes the time at which the gyro sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in gyro_x and gyro_y and gyro_z',
    2: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    3: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    4: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    5: 'Calibrated gyro reading',
    6: 'Calibrated gyro reading',
    7: 'Calibrated gyro reading',
    253: 'Whole second part of the timestamp',
  },
  165: {
    0: 'Millisecond part of the timestamp.',
    1: 'Each time in the array describes the time at which the accelerometer sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in accel_x and accel_y and accel_z',
    2: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    3: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    4: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    5: 'Calibrated accel reading',
    6: 'Calibrated accel reading',
    7: 'Calibrated accel reading',
    8: 'Calibrated accel reading',
    9: 'Calibrated accel reading',
    10: 'Calibrated accel reading',
    253: 'Whole second part of the timestamp',
  },
  167: {
    0: 'Indicates which sensor the calibration is for',
    1: 'Calibration factor used to convert from raw ADC value to degrees, g, etc.',
    2: 'Calibration factor divisor',
    3: 'Level shift value used to shift the ADC value back into range',
    4: 'Internal calibration factors, one for each: xy, yx, zx',
    5: '3 x 3 rotation matrix (row major)',
    253: 'Whole second part of the timestamp',
  },
  169: {
    0: 'Millisecond part of the timestamp.',
    1: 'Number of the frame that the timestamp and timestamp_ms correlate to',
    253: 'Whole second part of the timestamp',
  },
  174: {
    0: 'Fractional part of timestamp, added to timestamp',
    1: 'Offset of PID reading [i] from start_timestamp+start_timestamp_ms. Readings may span accross seconds.',
    2: 'Parameter ID',
    3: 'Raw parameter data',
    4: 'Optional, data size of PID[i]. If not specified refer to SAE J1979.',
    5: 'System time associated with sample expressed in ms, can be used instead of time_offset. There will be a system_time value for each raw_data element. For multibyte pids the system_time is repeated.',
    6: 'Timestamp of first sample recorded in the message. Used with time_offset to generate time of each sample',
    7: 'Fractional part of start_timestamp',
    253: 'Timestamp message was output',
  },
  177: {
    0: 'Fractional part of timestamp, added to timestamp',
    1: 'NMEA sentence',
    253: 'Timestamp message was output',
  },
  178: {
    0: 'Fractional part of timestamp, added to timestamp',
    1: 'System time associated with sample expressed in ms.',
    2: 'Range -PI/2 to +PI/2',
    3: 'Range -PI to +PI',
    4: 'Range -78.4 to +78.4 (-8 Gs to 8 Gs)',
    5: 'Range -78.4 to +78.4 (-8 Gs to 8 Gs)',
    6: 'Range -8.727 to +8.727 (-500 degs/sec to +500 degs/sec)',
    8: 'The percent complete of the current attitude stage. Set to 0 for attitude stages 0, 1 and 2 and to 100 for attitude stage 3 by AHRS modules that do not support it. Range - 100',
    9: 'Track Angle/Heading Range 0 - 2pi',
    253: 'Timestamp message was output',
  },
  184: {
    2: 'Playback time of video',
  },
  185: {
    0: 'Total number of title parts',
    254: 'Long titles will be split into multiple parts',
  },
  186: {
    0: 'Total number of description parts',
    254: 'Long descriptions will be split into multiple parts',
  },
  187: {
    6: 'Start of clip in video time',
    7: 'End of clip in video time',
  },
  200: {
    1: 'number of fields in screen',
  },
  208: {
    0: 'Millisecond part of the timestamp.',
    1: 'Each time in the array describes the time at which the compass sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in cmps_x and cmps_y and cmps_z',
    2: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    3: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    4: 'These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.',
    5: 'Calibrated Magnetometer reading',
    6: 'Calibrated Magnetometer reading',
    7: 'Calibrated Magnetometer reading',
    253: 'Whole second part of the timestamp',
  },
  209: {
    0: 'Millisecond part of the timestamp.',
    1: 'Each time in the array describes the time at which the barometer sample with the corrosponding index was taken. The samples may span across seconds. Array size must match the number of samples in baro_cal',
    2: 'These are the raw ADC reading. The samples may span across seconds. A conversion will need to be done on this data once read.',
    253: 'Whole second part of the timestamp',
  },
  210: {
    0: 'Indicates which sensor the calibration is for',
    1: 'Calibration factor used to convert from raw ADC value to degrees, g, etc.',
    2: 'Calibration factor divisor',
    3: 'Level shift value used to shift the ADC value back into range',
    4: 'Internal Calibration factor',
    253: 'Whole second part of the timestamp',
  },
  211: {
    0: '7-day rolling average',
    1: 'RHR for today only. (Feeds into 7-day average)',
    253:
        'Must align to logging interval, for example, time must be 00:00:00 for daily log.',
  },
  225: {
    3: '# of repitions of the movement',
    4: 'Amount of weight applied for the set',
    6: 'Start time of the set',
    8: 'Based on the associated category, see [category]_exercise_names',
    254: 'Timestamp of the set',
  },
  227: {
    1: 'Time stress score was calculated',
  },
  229: {
    0: 'Time maxMET and vo2 were calculated',
    9: 'Indicates if calibrated data was used in the calculation',
    12: 'Indicates if the estimate was obtained using a chest strap or wrist heart rate',
    13: 'Indidcates if the estimate was obtained using onboard GPS or connected GPS',
  },
  258: {
    5: 'Fresh water is usually 1000; salt water is usually 1025',
    6: 'Typically 1.40',
    7: 'Typically 1.60',
    17: 'Time between surfacing and ending the activity',
    18: 'Time at safety stop (if enabled)',
    21: 'Index of travel dive_gas message',
    22: 'If low PO2 should be switched to automatically',
    23: 'Target PO2 when using low setpoint',
    24: 'Depth to switch to low setpoint in automatic mode',
    25: 'If high PO2 should be switched to automatically',
    26: 'Target PO2 when using high setpoint',
    27: 'Depth to switch to high setpoint in automatic mode',
    29: 'Type of gas consumption rate to display. Some values are only valid if tank volume is known.',
    30: 'Indicates whether the up key is enabled during dives',
    35: 'Sounds and vibration enabled or disabled in-dive',
    36: 'Usually 1.0/1.5/2.0 representing 3/4.5/6m or 10/15/20ft',
    37: 'Indicates which guidelines to use for no-fly surface interval.',
  },
  262: {
    0: 'Depth setting (m) for depth type alarms',
    1: 'Time setting (s) for time type alarms',
    2: 'Enablement flag',
    3: 'Alarm type setting',
    4: 'Tone and Vibe setting for the alarm',
    5: 'Dive types the alarm will trigger on',
    6: 'Alarm ID',
    7: 'Show a visible pop-up for this alarm',
    8: 'Trigger the alarm on descent',
    9: 'Trigger the alarm on ascent',
    10: 'Repeat alarm each time threshold is crossed?',
    11: 'Ascent/descent rate (mps) setting for speed type alarms',
    254: 'Index of the alarm',
  },
  268: {
    2: '0 if above water',
    3: '0 if above water',
    4: 'Time since end of last dive',
    12: 'Average pressure-based surface air consumption',
    13: 'Average volumetric surface air consumption',
    14: 'Average respiratory minute volume',
    15: 'Time to reach deepest level stop',
    16: 'Time after leaving bottom until reaching surface',
    17: 'Average ascent rate, not including descents or stops',
    22: 'Average descent rate, not including ascents or stops',
    23: 'Maximum ascent rate',
    24: 'Maximum descent rate',
    25: 'Time spent neither ascending nor descending',
  },
  269: {
    2: 'Mode when data was captured',
  },
  285: {
    4: 'A score for a jump calculated based on hang time, rotations, and distance.',
  },
  289: {
    0: 'Time interval length in seconds',
    1: 'Total accelerometer energy in the interval',
    2: 'Count of zero crossings',
    3: 'Instance ID of zero crossing algorithm',
    4: 'Total accelerometer time above threshold in the interval',
  },
  290: {
    0: 'Milliseconds past date_time',
    1: 'Array of millisecond times between beats',
  },
  297: {
    0: 'Breaths * 100 /min, -300 indicates invalid, -200 indicates large motion, -100 indicates off wrist',
  },
  302: {
    0: 'Millisecond resolution of the timestamp',
    1: 'Sampling Interval in Milliseconds',
    2: 'X-Axis Measurement',
    3: 'Y-Axis Measurement',
    4: 'Z-Axis Measurement',
    5: '32 kHz timestamp',
  },
  304: {
    0: 'Processing interval length in seconds. File start: 0xFFFFFFEF File stop: 0xFFFFFFEE',
    1: 'Total step sum',
  },
  305: {
    0: 'Processing interval length in seconds',
    1: 'SpO2 Reading: [70,100] Blank: 240',
    2: 'SpO2 Confidence: [0,254]',
  },
  306: {
    0: 'Processing interval length in seconds',
    1: 'Stress Level: [0,100] Off wrist: -1 Excess motion: -2 Not enough data: -3 Recovering from exercise: -4 Unidentified: -5 Blank: -16',
  },
  307: {
    0: 'Processing interval length in seconds',
    1: 'Breaths / min: [1,100] Invalid: 255 Excess motion: 254 Off wrist: 253 Not available: 252 Blank: 2.4',
  },
  308: {
    0: 'Processing interval length in seconds',
    1: 'Status of measurements in buffer - 0 indicates SEARCHING 1 indicates LOCKED',
    2: 'Beats / min. Blank: 0',
  },
  312: {
    78: 'Active time of split rounds',
  },
  313: {
    65: 'total active time in all split rounds',
  },
  314: {
    0: 'Processing interval length in seconds',
    1: 'Body battery level: [0,100] Blank: -16',
    2: 'Body battery charged value',
    3: 'Body battery uncharged value',
  },
  315: {
    0: 'Event ID. Health SDK use only',
  },
  346: {
    0: 'Average of awake_time_score and awakenings_count_score. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    1: 'Score that evaluates the total time spent awake between sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    2: 'Score that evaluates the number of awakenings that interrupt sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    3: 'Score that evaluates the amount of deep sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    4: 'Score that evaluates the quality of sleep based on sleep stages, heart-rate variability and possible awakenings during the night. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    5: 'Score that evaluates the amount of light sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    6: 'Total score that summarizes the overall quality of sleep, combining sleep duration and quality. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    7: 'Score that evaluates the quality of sleep based on sleep stages, heart-rate variability and possible awakenings during the night. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    8: 'Score that evaluates stress and recovery during sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    9: 'Score that evaluates the amount of REM sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    10: 'Score that evaluates the amount of restlessness during sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    11: 'The number of awakenings during sleep.',
    14: 'Score that evaluates the sleep interruptions. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.',
    15: 'Excludes stress during awake periods in the sleep window',
  },
  370: {
    0: '7 day RMSSD average over sleep',
    1: 'Last night RMSSD average over sleep',
    2: '5 minute high RMSSD value over sleep',
    3: '3 week baseline, upper boundary of low HRV status',
    4: '3 week baseline, lower boundary of balanced HRV status',
    5: '3 week baseline, upper boundary of balanced HRV status',
  },
  371: {
    0: '5 minute RMSSD',
  },
  372: {
    0: 'Millisecond resolution of the timestamp',
    1: '1 bit for gap indicator, 1 bit for quality indicator, and 14 bits for Beat-to-Beat interval values in whole-integer millisecond resolution',
    2: 'Array of millisecond times between beats',
    3: '1 = high confidence. 0 = low confidence. N/A when gap = 1',
    4: '1 = gap (time represents ms gap length). 0 = BBI data',
  },
  376: {
    0: 'Millisecond resolution of the timestamp',
    1: 'Sampling Interval in 32 kHz timescale',
    2: 'X-Axis Measurement',
    3: 'Y-Axis Measurement',
    4: 'Z-Axis Measurement',
    5: '32 kHz timestamp',
  },
  389: {
    0: 'Encoded configuration data. Health SDK use only',
    1: 'Size in bytes of data field',
    253: 'Encoded configuration data',
  },
  393: {
    0: 'Depth setting (m) for depth type alarms',
    1: 'Time setting (s) for time type alarms',
    2: 'Enablement flag',
    3: 'Alarm type setting',
    4: 'Tone and Vibe setting for the alarm.',
    5: 'Dive types the alarm will trigger on',
    6: 'Alarm ID',
    7: 'Show a visible pop-up for this alarm',
    8: 'Trigger the alarm on descent',
    9: 'Trigger the alarm on ascent',
    10: 'Repeat alarm each time threshold is crossed?',
    11: 'Ascent/descent rate (mps) setting for speed type alarms',
    254: 'Index of the alarm',
  },
  398: {
    1: 'The average overnight deviation from baseline temperature in degrees C',
    2: 'The average 7 day overnight deviation from baseline temperature in degrees C',
    4: 'Final overnight temperature value',
  },
  409: {
    0: 'Processing interval length in seconds',
    1: 'Wrist temperature reading',
  },
  412: {
    7: 'The timestamp representing when this nap event was last updated',
  },
};

/// Comment on each documented subfield, by message number, field
/// number, then subfield name.
const Map<int, Map<int, Map<String, String>>> profileSubfieldDocs = {
  18: {
    10: {
      'TotalPushes': 'total number of pushes in a session',
    },
  },
  21: {
    3: {
      'RadarThreatAlert':
          'The first byte is the radar_threat_level_max, the second byte is the radar_threat_count, third bytes is the average approach speed, and the 4th byte is the max approach speed',
      'RiderPosition': 'Indicates the rider position value.',
    },
    15: {
      'AutoActivityDetectStartTimestamp':
          'Auto Activity Detect Start Timestamp.',
    },
  },
  27: {
    2: {
      'DurationStep':
          'message_index of step to loop back to. Steps are assumed to be in the order by message_index. custom_name and intensity members are undefined for this duration type.',
    },
    4: {
      'RepeatSteps': '# of repetitions',
      'TargetCadenceZone': 'Zone (1-?); Custom = 0;',
      'TargetHrZone': 'hr zone (1-5);Custom =0;',
      'TargetPowerZone': 'Power Zone ( 1-7); Custom = 0;',
      'TargetSpeedZone': 'speed zone (1-10);Custom =0;',
    },
    20: {
      'SecondaryTargetCadenceZone': 'Zone (1-?); Custom = 0;',
      'SecondaryTargetHrZone': 'hr zone (1-5);Custom =0;',
      'SecondaryTargetPowerZone': 'Power Zone ( 1-7); Custom = 0;',
      'SecondaryTargetSpeedZone': 'speed zone (1-10);Custom =0;',
    },
  },
  167: {
    1: {
      'AccelCalFactor': 'Accelerometer calibration factor',
      'GyroCalFactor': 'Gyro calibration factor',
    },
  },
  210: {
    1: {
      'BaroCalFactor': 'Barometer calibration factor',
    },
  },
};

/// FIT base type each profile type is stored as (e.g. `enum`,
/// `uint32z`), by [ProfileType].
const Map<ProfileType, String> profileTypeBaseTypes = {
  ProfileType.activity: 'enum',
  ProfileType.activityClass: 'enum',
  ProfileType.activityLevel: 'enum',
  ProfileType.activitySubtype: 'enum',
  ProfileType.activityType: 'enum',
  ProfileType.analogWatchfaceLayout: 'enum',
  ProfileType.antChannelId: 'uint32z',
  ProfileType.antNetwork: 'enum',
  ProfileType.antplusDeviceType: 'uint8',
  ProfileType.attitudeStage: 'enum',
  ProfileType.attitudeValidity: 'uint16',
  ProfileType.autoActivityDetect: 'uint32',
  ProfileType.autoSyncFrequency: 'enum',
  ProfileType.autolapTrigger: 'enum',
  ProfileType.autoscroll: 'enum',
  ProfileType.backlightMode: 'enum',
  ProfileType.backlightTimeout: 'uint8',
  ProfileType.bandedExercisesExerciseName: 'uint16',
  ProfileType.batteryStatus: 'uint8',
  ProfileType.battleRopeExerciseName: 'uint16',
  ProfileType.benchPressExerciseName: 'uint16',
  ProfileType.bikeExerciseName: 'uint16',
  ProfileType.bikeLightBeamAngleMode: 'uint8',
  ProfileType.bikeLightNetworkConfigType: 'enum',
  ProfileType.bikeOutdoorExerciseName: 'uint16',
  ProfileType.bleDeviceType: 'uint8',
  ProfileType.bodyLocation: 'enum',
  ProfileType.bpStatus: 'enum',
  ProfileType.calfRaiseExerciseName: 'uint16',
  ProfileType.cameraEventType: 'enum',
  ProfileType.cameraOrientationType: 'enum',
  ProfileType.cardioExerciseName: 'uint16',
  ProfileType.carryExerciseName: 'uint16',
  ProfileType.ccrSetpointSwitchMode: 'enum',
  ProfileType.checksum: 'uint8',
  ProfileType.chopExerciseName: 'uint16',
  ProfileType.climbProEvent: 'enum',
  ProfileType.commTimeoutType: 'uint16',
  ProfileType.connectivityCapabilities: 'uint32z',
  ProfileType.coreExerciseName: 'uint16',
  ProfileType.courseCapabilities: 'uint32z',
  ProfileType.coursePoint: 'enum',
  ProfileType.crunchExerciseName: 'uint16',
  ProfileType.curlExerciseName: 'uint16',
  ProfileType.dateMode: 'enum',
  ProfileType.dateTime: 'uint32',
  ProfileType.dayOfWeek: 'enum',
  ProfileType.deadliftExerciseName: 'uint16',
  ProfileType.deviceIndex: 'uint8',
  ProfileType.digitalWatchfaceLayout: 'enum',
  ProfileType.displayHeart: 'enum',
  ProfileType.displayMeasure: 'enum',
  ProfileType.displayOrientation: 'enum',
  ProfileType.displayPosition: 'enum',
  ProfileType.displayPower: 'enum',
  ProfileType.diveAlarmType: 'enum',
  ProfileType.diveAlert: 'enum',
  ProfileType.diveBacklightMode: 'enum',
  ProfileType.diveGasMode: 'enum',
  ProfileType.diveGasStatus: 'enum',
  ProfileType.ellipticalExerciseName: 'uint16',
  ProfileType.event: 'enum',
  ProfileType.eventType: 'enum',
  ProfileType.exdDataUnits: 'enum',
  ProfileType.exdDescriptors: 'enum',
  ProfileType.exdDisplayType: 'enum',
  ProfileType.exdLayout: 'enum',
  ProfileType.exdQualifiers: 'enum',
  ProfileType.exerciseCategory: 'uint16',
  ProfileType.faveroProduct: 'uint16',
  ProfileType.file: 'enum',
  ProfileType.fileFlags: 'uint8z',
  ProfileType.fitBaseType: 'uint8',
  ProfileType.fitBaseUnit: 'uint16',
  ProfileType.fitnessEquipmentState: 'enum',
  ProfileType.floorClimbExerciseName: 'uint16',
  ProfileType.flyeExerciseName: 'uint16',
  ProfileType.garminProduct: 'uint16',
  ProfileType.gasConsumptionRateType: 'enum',
  ProfileType.gender: 'enum',
  ProfileType.goal: 'enum',
  ProfileType.goalRecurrence: 'enum',
  ProfileType.goalSource: 'enum',
  ProfileType.hipRaiseExerciseName: 'uint16',
  ProfileType.hipStabilityExerciseName: 'uint16',
  ProfileType.hipSwingExerciseName: 'uint16',
  ProfileType.hrType: 'enum',
  ProfileType.hrZoneCalc: 'enum',
  ProfileType.hrvStatus: 'enum',
  ProfileType.hyperextensionExerciseName: 'uint16',
  ProfileType.indoorBikeExerciseName: 'uint16',
  ProfileType.indoorRowExerciseName: 'uint16',
  ProfileType.intensity: 'enum',
  ProfileType.ladderExerciseName: 'uint16',
  ProfileType.language: 'enum',
  ProfileType.languageBits0: 'uint8z',
  ProfileType.languageBits1: 'uint8z',
  ProfileType.languageBits2: 'uint8z',
  ProfileType.languageBits3: 'uint8z',
  ProfileType.languageBits4: 'uint8z',
  ProfileType.lapTrigger: 'enum',
  ProfileType.lateralRaiseExerciseName: 'uint16',
  ProfileType.leftRightBalance: 'uint8',
  ProfileType.leftRightBalance100: 'uint16',
  ProfileType.legCurlExerciseName: 'uint16',
  ProfileType.legRaiseExerciseName: 'uint16',
  ProfileType.lengthType: 'enum',
  ProfileType.localDateTime: 'uint32',
  ProfileType.localDeviceType: 'uint8',
  ProfileType.localtimeIntoDay: 'uint32',
  ProfileType.lungeExerciseName: 'uint16',
  ProfileType.manufacturer: 'uint16',
  ProfileType.maxMetCategory: 'enum',
  ProfileType.maxMetHeartRateSource: 'enum',
  ProfileType.maxMetSpeedSource: 'enum',
  ProfileType.mesgCount: 'enum',
  ProfileType.mesgNum: 'uint16',
  ProfileType.messageIndex: 'uint16',
  ProfileType.moveExerciseName: 'uint16',
  ProfileType.napPeriodFeedback: 'enum',
  ProfileType.napSource: 'enum',
  ProfileType.noFlyTimeMode: 'enum',
  ProfileType.olympicLiftExerciseName: 'uint16',
  ProfileType.plankExerciseName: 'uint16',
  ProfileType.plyoExerciseName: 'uint16',
  ProfileType.poseExerciseName: 'uint16',
  ProfileType.powerPhaseType: 'enum',
  ProfileType.projectileType: 'enum',
  ProfileType.pullUpExerciseName: 'uint16',
  ProfileType.pushUpExerciseName: 'uint16',
  ProfileType.pwrZoneCalc: 'enum',
  ProfileType.radarThreatLevelType: 'enum',
  ProfileType.riderPositionType: 'enum',
  ProfileType.rowExerciseName: 'uint16',
  ProfileType.runExerciseName: 'uint16',
  ProfileType.runIndoorExerciseName: 'uint16',
  ProfileType.sandbagExerciseName: 'uint16',
  ProfileType.schedule: 'enum',
  ProfileType.segmentDeleteStatus: 'enum',
  ProfileType.segmentLapStatus: 'enum',
  ProfileType.segmentLeaderboardType: 'enum',
  ProfileType.segmentSelectionType: 'enum',
  ProfileType.sensorType: 'enum',
  ProfileType.sessionTrigger: 'enum',
  ProfileType.setType: 'uint8',
  ProfileType.shoulderPressExerciseName: 'uint16',
  ProfileType.shoulderStabilityExerciseName: 'uint16',
  ProfileType.shrugExerciseName: 'uint16',
  ProfileType.side: 'enum',
  ProfileType.sitUpExerciseName: 'uint16',
  ProfileType.sledExerciseName: 'uint16',
  ProfileType.sledgeHammerExerciseName: 'uint16',
  ProfileType.sleepDisruptionSeverity: 'enum',
  ProfileType.sleepLevel: 'enum',
  ProfileType.sourceType: 'enum',
  ProfileType.splitType: 'enum',
  ProfileType.spo2MeasurementType: 'enum',
  ProfileType.sport: 'enum',
  ProfileType.sportBits0: 'uint8z',
  ProfileType.sportBits1: 'uint8z',
  ProfileType.sportBits2: 'uint8z',
  ProfileType.sportBits3: 'uint8z',
  ProfileType.sportBits4: 'uint8z',
  ProfileType.sportBits5: 'uint8z',
  ProfileType.sportBits6: 'uint8z',
  ProfileType.sportEvent: 'enum',
  ProfileType.squatExerciseName: 'uint16',
  ProfileType.stairStepperExerciseName: 'uint16',
  ProfileType.strokeType: 'enum',
  ProfileType.subSport: 'enum',
  ProfileType.supportedExdScreenLayouts: 'uint32z',
  ProfileType.suspensionExerciseName: 'uint16',
  ProfileType.swimStroke: 'enum',
  ProfileType.switch_: 'enum',
  ProfileType.tapSensitivity: 'enum',
  ProfileType.timeIntoDay: 'uint32',
  ProfileType.timeMode: 'enum',
  ProfileType.timeZone: 'enum',
  ProfileType.timerTrigger: 'enum',
  ProfileType.tireExerciseName: 'uint16',
  ProfileType.tissueModelType: 'enum',
  ProfileType.tone: 'enum',
  ProfileType.totalBodyExerciseName: 'uint16',
  ProfileType.tricepsExtensionExerciseName: 'uint16',
  ProfileType.turnType: 'enum',
  ProfileType.userLocalId: 'uint16',
  ProfileType.warmUpExerciseName: 'uint16',
  ProfileType.watchfaceMode: 'enum',
  ProfileType.waterType: 'enum',
  ProfileType.weatherReport: 'enum',
  ProfileType.weatherSevereType: 'enum',
  ProfileType.weatherSeverity: 'enum',
  ProfileType.weatherStatus: 'enum',
  ProfileType.weight: 'uint16',
  ProfileType.wktStepDuration: 'enum',
  ProfileType.wktStepTarget: 'enum',
  ProfileType.workoutCapabilities: 'uint32z',
  ProfileType.workoutEquipment: 'enum',
  ProfileType.workoutHr: 'uint32',
  ProfileType.workoutPower: 'uint32',
};

/// Comment on each documented profile type, by [ProfileType].
const Map<ProfileType, String> profileTypeDocs = {
  ProfileType.backlightTimeout: 'Timeout in seconds.',
  ProfileType.dateTime: 'seconds since UTC 00:00 Dec 31 1989',
  ProfileType.fitnessEquipmentState: 'fitness equipment event data',
  ProfileType.languageBits0:
      'Bit field corresponding to language enum type (1 << language).',
  ProfileType.localDateTime:
      'seconds since 00:00 Dec 31 1989 in local time zone',
  ProfileType.localtimeIntoDay:
      'number of seconds into the day since local 00:00:00',
  ProfileType.sportBits0:
      'Bit field corresponding to sport enum type (1 << sport).',
  ProfileType.sportBits1:
      'Bit field corresponding to sport enum type (1 << (sport-8)).',
  ProfileType.sportBits2:
      'Bit field corresponding to sport enum type (1 << (sport-16)).',
  ProfileType.sportBits3:
      'Bit field corresponding to sport enum type (1 << (sport-24)).',
  ProfileType.sportBits4:
      'Bit field corresponding to sport enum type (1 << (sport-32)).',
  ProfileType.sportBits5:
      'Bit field corresponding to sport enum type (1 << (sport-40)).',
  ProfileType.sportBits6:
      'Bit field corresponding to sport enum type (1 << (sport-48)).',
  ProfileType.timeIntoDay: 'number of seconds into the day since 00:00:00 UTC',
  ProfileType.timerTrigger: 'timer event data',
  ProfileType.workoutHr:
      '0 - 100 indicates% of max hr; >100 indicates bpm (255 max) plus 100',
  ProfileType.workoutPower:
      '0 - 1000 indicates % of functional threshold power; >1000 indicates watts plus 1000.',
};

/// Comment on each documented enum value, by [ProfileType], value,
/// then value name as Profile.xlsx spells it (e.g. `OHR`). The name
/// only tells apart names sharing a value (`forecast` and
/// `hourly_forecast`). Scalar types (dateTime, ...) have no value
/// table, so their sentinel values are left out.
const Map<ProfileType, Map<int, Map<String, String>>> profileValueDocs = {
  ProfileType.activityClass: {
    127: {
      'level': '0 to 100',
    },
  },
  ProfileType.activitySubtype: {
    1: {
      'treadmill': 'Run',
    },
    2: {
      'street': 'Run',
    },
    3: {
      'trail': 'Run',
    },
    4: {
      'track': 'Run',
    },
    5: {
      'spin': 'Cycling',
    },
    6: {
      'indoor_cycling': 'Cycling',
    },
    7: {
      'road': 'Cycling',
    },
    8: {
      'mountain': 'Cycling',
    },
    9: {
      'downhill': 'Cycling',
    },
    10: {
      'recumbent': 'Cycling',
    },
    11: {
      'cyclocross': 'Cycling',
    },
    12: {
      'hand_cycling': 'Cycling',
    },
    13: {
      'track_cycling': 'Cycling',
    },
    14: {
      'indoor_rowing': 'Fitness Equipment',
    },
    15: {
      'elliptical': 'Fitness Equipment',
    },
    16: {
      'stair_climbing': 'Fitness Equipment',
    },
    17: {
      'lap_swimming': 'Swimming',
    },
    18: {
      'open_water': 'Swimming',
    },
  },
  ProfileType.activityType: {
    3: {
      'transition': 'Mulitsport transition',
    },
    254: {
      'all': 'All is for goals only to include all sports.',
    },
  },
  ProfileType.backlightTimeout: {
    0: {
      'infinite': 'Backlight stays on forever.',
    },
  },
  ProfileType.bleDeviceType: {
    0: {
      'connected_gps':
          'GPS that is provided over a proprietary bluetooth service',
    },
    7: {
      'bike_trainer': 'Indoor-Bike FTMS protocol',
    },
  },
  ProfileType.bodyLocation: {
    26: {
      'left_brachioradialis': 'Left anterior forearm',
    },
    27: {
      'left_forearm_extensors': 'Left posterior forearm',
    },
    32: {
      'right_brachioradialis': 'Right anterior forearm',
    },
    33: {
      'right_forearm_extensors': 'Right posterior forearm',
    },
  },
  ProfileType.cameraEventType: {
    0: {
      'video_start': 'Start of video recording',
    },
    1: {
      'video_split':
          'Mark of video file split (end of one file, beginning of the other)',
    },
    2: {
      'video_end': 'End of video recording',
    },
    3: {
      'photo_taken': 'Still photo taken',
    },
    7: {
      'video_split_start': 'Mark of video file split start',
    },
    11: {
      'video_pause': 'Mark when a video recording has been paused',
    },
    13: {
      'video_resume': 'Mark when a video recording has been resumed',
    },
  },
  ProfileType.ccrSetpointSwitchMode: {
    0: {
      'manual': 'User switches setpoints manually',
    },
    1: {
      'automatic': 'Switch automatically based on depth',
    },
  },
  ProfileType.checksum: {
    0: {
      'clear':
          'Allows clear of checksum for flash memory where can only write 1 to 0 without erasing sector.',
    },
    1: {
      'ok':
          'Set to mark checksum as valid if computes to invalid values 0 or 0xFF. Checksum can also be set to ok to save encoding computation time.',
    },
  },
  ProfileType.commTimeoutType: {
    0: {
      'wildcard_pairing_timeout': 'Timeout pairing to any device',
    },
    1: {
      'pairing_timeout': 'Timeout pairing to previously paired device',
    },
    2: {
      'connection_lost': 'Temporary loss of communications',
    },
    3: {
      'connection_timeout':
          'Connection closed due to extended bad communications',
    },
  },
  ProfileType.connectivityCapabilities: {
    32768: {
      'device_initiates_sync':
          'Indicates device is in control of initiating all syncs',
    },
    1048576: {
      'connect_iq_app_managment':
          'Device supports delete and reorder of apps via GCM',
    },
    8388608: {
      'incident_detection': 'Device supports incident detection',
    },
    33554432: {
      'wifi_verification':
          'Device supports reporting wifi verification via GCM',
    },
    67108864: {
      'true_up': 'Device supports True Up',
    },
    134217728: {
      'find_my_watch': 'Device supports Find My Watch',
    },
    536870912: {
      'live_track_auto_start': 'Device supports LiveTrack auto start',
    },
    1073741824: {
      'live_track_messaging': 'Device supports LiveTrack Messaging',
    },
    2147483648: {
      'instant_input': 'Device supports instant input feature',
    },
  },
  ProfileType.coreExerciseName: {
    47: {
      'abdominal_leg_rotations': 'Deprecated do not use',
    },
    54: {
      'criss_cross_with_ball': 'Deprecated do not use',
    },
    68: {
      'snake_twist_1_and_2': 'Deprecated do not use',
    },
  },
  ProfileType.courseCapabilities: {
    4096: {
      'aviation': 'Denote course files to be used as flight plans',
    },
  },
  ProfileType.coursePoint: {
    30: {
      'general_distance': 'Used with UpAhead',
    },
  },
  ProfileType.deviceIndex: {
    0: {
      'creator': 'Creator of the file is always device index 0.',
    },
  },
  ProfileType.displayOrientation: {
    0: {
      'auto': 'automatic if the device supports it',
    },
    3: {
      'portrait_flipped': 'portrait mode but rotated 180 degrees',
    },
    4: {
      'landscape_flipped': 'landscape mode but rotated 180 degrees',
    },
  },
  ProfileType.displayPosition: {
    0: {
      'degree': 'dd.dddddd',
    },
    1: {
      'degree_minute': 'dddmm.mmm',
    },
    2: {
      'degree_minute_second': 'dddmmss',
    },
    3: {
      'austrian_grid': 'Austrian Grid (BMN)',
    },
    4: {
      'british_grid': 'British National Grid',
    },
    5: {
      'dutch_grid': 'Dutch grid system',
    },
    6: {
      'hungarian_grid': 'Hungarian grid system',
    },
    7: {
      'finnish_grid': 'Finnish grid system Zone3 KKJ27',
    },
    8: {
      'german_grid': 'Gausss Krueger (German)',
    },
    9: {
      'icelandic_grid': 'Icelandic Grid',
    },
    10: {
      'indonesian_equatorial': 'Indonesian Equatorial LCO',
    },
    11: {
      'indonesian_irian': 'Indonesian Irian LCO',
    },
    12: {
      'indonesian_southern': 'Indonesian Southern LCO',
    },
    13: {
      'india_zone_0': 'India zone 0',
    },
    14: {
      'india_zone_IA': 'India zone IA',
    },
    15: {
      'india_zone_IB': 'India zone IB',
    },
    16: {
      'india_zone_IIA': 'India zone IIA',
    },
    17: {
      'india_zone_IIB': 'India zone IIB',
    },
    18: {
      'india_zone_IIIA': 'India zone IIIA',
    },
    19: {
      'india_zone_IIIB': 'India zone IIIB',
    },
    20: {
      'india_zone_IVA': 'India zone IVA',
    },
    21: {
      'india_zone_IVB': 'India zone IVB',
    },
    22: {
      'irish_transverse': 'Irish Transverse Mercator',
    },
    23: {
      'irish_grid': 'Irish Grid',
    },
    24: {
      'loran': 'Loran TD',
    },
    25: {
      'maidenhead_grid': 'Maidenhead grid system',
    },
    26: {
      'mgrs_grid': 'MGRS grid system',
    },
    27: {
      'new_zealand_grid': 'New Zealand grid system',
    },
    28: {
      'new_zealand_transverse': 'New Zealand Transverse Mercator',
    },
    29: {
      'qatar_grid': 'Qatar National Grid',
    },
    30: {
      'modified_swedish_grid': 'Modified RT-90 (Sweden)',
    },
    31: {
      'swedish_grid': 'RT-90 (Sweden)',
    },
    32: {
      'south_african_grid': 'South African Grid',
    },
    33: {
      'swiss_grid': 'Swiss CH-1903 grid',
    },
    34: {
      'taiwan_grid': 'Taiwan Grid',
    },
    35: {
      'united_states_grid': 'United States National Grid',
    },
    36: {
      'utm_ups_grid': 'UTM/UPS grid system',
    },
    37: {
      'west_malayan': 'West Malayan RSO',
    },
    38: {
      'borneo_rso': 'Borneo RSO',
    },
    39: {
      'estonian_grid': 'Estonian grid system',
    },
    40: {
      'latvian_grid': 'Latvian Transverse Mercator',
    },
    41: {
      'swedish_ref_99_grid': 'Reference Grid 99 TM (Swedish)',
    },
  },
  ProfileType.diveAlarmType: {
    0: {
      'depth': 'Alarm when a certain depth is crossed',
    },
    1: {
      'time': 'Alarm when a certain time has transpired',
    },
    2: {
      'speed': 'Alarm when a certain ascent or descent rate is exceeded',
    },
  },
  ProfileType.diveAlert: {
    33: {
      'po2_ccr_dil_low': 'ccr diluent has low po2',
    },
    34: {
      'deco_stop_cleared': 'a deco stop has been cleared',
    },
    35: {
      'apnea_neutral_buoyancy': 'Target Depth Apnea Alarm triggered',
    },
    36: {
      'apnea_target_depth': 'Neutral Buoyance Apnea Alarm triggered',
    },
    37: {
      'apnea_surface': 'Surface Apnea Alarm triggered',
    },
    38: {
      'apnea_high_speed': 'High Speed Apnea Alarm triggered',
    },
    39: {
      'apnea_low_speed': 'Low Speed Apnea Alarm triggered',
    },
  },
  ProfileType.event: {
    0: {
      'timer': 'Group 0. Start / stop_all',
    },
    3: {
      'workout': 'start / stop',
    },
    4: {
      'workout_step':
          'Start at beginning of workout. Stop at end of each step.',
    },
    5: {
      'power_down': 'stop_all group 0',
    },
    6: {
      'power_up': 'stop_all group 0',
    },
    7: {
      'off_course': 'start / stop group 0',
    },
    8: {
      'session': 'Stop at end of each session.',
    },
    9: {
      'lap': 'Stop at end of each lap.',
    },
    10: {
      'course_point': 'marker',
    },
    11: {
      'battery': 'marker',
    },
    12: {
      'virtual_partner_pace':
          'Group 1. Start at beginning of activity if VP enabled, when VP pace is changed during activity or VP enabled mid activity. stop_disable when VP disabled.',
    },
    13: {
      'hr_high_alert': 'Group 0. Start / stop when in alert condition.',
    },
    14: {
      'hr_low_alert': 'Group 0. Start / stop when in alert condition.',
    },
    15: {
      'speed_high_alert': 'Group 0. Start / stop when in alert condition.',
    },
    16: {
      'speed_low_alert': 'Group 0. Start / stop when in alert condition.',
    },
    17: {
      'cad_high_alert': 'Group 0. Start / stop when in alert condition.',
    },
    18: {
      'cad_low_alert': 'Group 0. Start / stop when in alert condition.',
    },
    19: {
      'power_high_alert': 'Group 0. Start / stop when in alert condition.',
    },
    20: {
      'power_low_alert': 'Group 0. Start / stop when in alert condition.',
    },
    21: {
      'recovery_hr': 'marker',
    },
    22: {
      'battery_low': 'marker',
    },
    23: {
      'time_duration_alert':
          'Group 1. Start if enabled mid activity (not required at start of activity). Stop when duration is reached. stop_disable if disabled.',
    },
    24: {
      'distance_duration_alert':
          'Group 1. Start if enabled mid activity (not required at start of activity). Stop when duration is reached. stop_disable if disabled.',
    },
    25: {
      'calorie_duration_alert':
          'Group 1. Start if enabled mid activity (not required at start of activity). Stop when duration is reached. stop_disable if disabled.',
    },
    26: {
      'activity': 'Group 1.. Stop at end of activity.',
    },
    27: {
      'fitness_equipment': 'marker',
    },
    28: {
      'length': 'Stop at end of each length.',
    },
    32: {
      'user_marker': 'marker',
    },
    33: {
      'sport_point': 'marker',
    },
    36: {
      'calibration': 'start/stop/marker',
    },
    42: {
      'front_gear_change': 'marker',
    },
    43: {
      'rear_gear_change': 'marker',
    },
    44: {
      'rider_position_change': 'marker',
    },
    45: {
      'elev_high_alert': 'Group 0. Start / stop when in alert condition.',
    },
    46: {
      'elev_low_alert': 'Group 0. Start / stop when in alert condition.',
    },
    47: {
      'comm_timeout': 'marker',
    },
    54: {
      'auto_activity_detect': 'marker',
    },
    56: {
      'dive_alert': 'marker',
    },
    57: {
      'dive_gas_switched': 'marker',
    },
    71: {
      'tank_pressure_reserve': 'marker',
    },
    72: {
      'tank_pressure_critical': 'marker',
    },
    73: {
      'tank_lost': 'marker',
    },
    75: {
      'radar_threat_alert': 'start/stop/marker',
    },
    76: {
      'tank_battery_low': 'marker',
    },
    81: {
      'tank_pod_connected': 'marker - tank pod has connected',
    },
    82: {
      'tank_pod_disconnected': 'marker - tank pod has lost connection',
    },
  },
  ProfileType.exdDescriptors: {
    65: {
      'gears': 'Combined gear information',
    },
  },
  ProfileType.exdLayout: {
    8: {
      'dynamic':
          'The EXD may display the configured concepts in any layout it sees fit.',
    },
  },
  ProfileType.exerciseCategory: {
    34: {
      'cardio_sensors':
          'Exercises within workouts that use GPS/sensors rather than rep counting',
    },
  },
  ProfileType.file: {
    1: {
      'device': 'Read only, single file. Must be in root directory.',
    },
    2: {
      'settings': 'Read/write, single file. Directory=Settings',
    },
    3: {
      'sport':
          'Read/write, multiple files, file number = sport type. Directory=Sports',
    },
    4: {
      'activity': 'Read/erase, multiple files. Directory=Activities',
    },
    5: {
      'workout': 'Read/write/erase, multiple files. Directory=Workouts',
    },
    6: {
      'course': 'Read/write/erase, multiple files. Directory=Courses',
    },
    7: {
      'schedules': 'Read/write, single file. Directory=Schedules',
    },
    9: {
      'weight':
          'Read only, single file. Circular buffer. All message definitions at start of file. Directory=Weight',
    },
    10: {
      'totals': 'Read only, single file. Directory=Totals',
    },
    11: {
      'goals': 'Read/write, single file. Directory=Goals',
    },
    14: {
      'blood_pressure': 'Read only. Directory=Blood Pressure',
    },
    15: {
      'monitoring_a': 'Read only. Directory=Monitoring. File number=sub type.',
    },
    20: {
      'activity_summary': 'Read/erase, multiple files. Directory=Activities',
    },
    32: {
      'monitoring_b': 'Read only. Directory=Monitoring. File number=identifier',
    },
    34: {
      'segment': 'Read/write/erase. Multiple Files. Directory=Segments',
    },
    35: {
      'segment_list': 'Read/write/erase. Single File. Directory=Segments',
    },
    40: {
      'exd_configuration': 'Read/write/erase. Single File. Directory=Settings',
    },
    247: {
      'mfg_range_min':
          '0xF7 - 0xFE reserved for manufacturer specific file types',
    },
    254: {
      'mfg_range_max':
          '0xF7 - 0xFE reserved for manufacturer specific file types',
    },
  },
  ProfileType.fitnessEquipmentState: {
    3: {
      'unknown': 'lost connection to fitness equipment',
    },
  },
  ProfileType.garminProduct: {
    2: {
      'axh01': 'AXH01 HRM chipset',
    },
    8: {
      'hrm_run_single_byte_product_id': 'hrm_run model for HRM ANT+ messaging',
    },
    9: {
      'bsm': 'BSM model for ANT+ messaging',
    },
    10: {
      'bcm': 'BCM model for ANT+ messaging',
    },
    11: {
      'axs01': 'AXS01 HRM Bike Chipset model for ANT+ messaging',
    },
    12: {
      'hrm_tri_single_byte_product_id': 'hrm_tri model for HRM ANT+ messaging',
    },
    13: {
      'hrm4_run_single_byte_product_id':
          'hrm4 run model for HRM ANT+ messaging',
    },
    14: {
      'fr225_single_byte_product_id': 'fr225 model for HRM ANT+ messaging',
    },
    15: {
      'gen3_bsm_single_byte_product_id':
          'gen3_bsm model for Bike Speed ANT+ messaging',
    },
    16: {
      'gen3_bcm_single_byte_product_id':
          'gen3_bcm model for Bike Cadence ANT+ messaging',
    },
    255: {
      'OHR':
          'Garmin Wearable Optical Heart Rate Sensor for ANT+ HR Profile Broadcasting',
    },
    717: {
      'fr405': 'Forerunner 405',
    },
    782: {
      'fr50': 'Forerunner 50',
    },
    988: {
      'fr60': 'Forerunner 60',
    },
    1018: {
      'fr310xt': 'Forerunner 310',
    },
    1124: {
      'fr110': 'Forerunner 110',
    },
    1736: {
      'edge_touring': 'Also Edge Touring Plus',
    },
    1743: {
      'hrm_tri': 'Also HRM-Swim',
    },
    2567: {
      'varia_ut800': 'Varia UT 800 SW',
    },
    3192: {
      'gen3_bsm': 'gen3 bike speed sensor',
    },
    3193: {
      'gen3_bcm': 'gen3 bike cadence sensor',
    },
    3299: {
      'hrm_dual': 'HRM-Dual',
    },
    3300: {
      'hrm_pro': 'HRM-Pro',
    },
    3578: {
      'rally_200': 'Rally 100/200 Power Meter Series',
    },
    3702: {
      'descent_mk2_asia': 'Mk2 and Mk2i',
    },
    3865: {
      'gnss': 'Airoha AG3335M Family',
    },
    4105: {
      'marq_gen2': 'Adventurer, Athlete, Captain, Golfer',
    },
    4265: {
      'tacx_neo_smart': 'Neo Smart, Tacx',
    },
    4266: {
      'tacx_neo2_smart': 'Neo 2 Smart, Tacx',
    },
    4267: {
      'tacx_neo2_t_smart': 'Neo 2T Smart, Tacx',
    },
    4268: {
      'tacx_neo_smart_bike': 'Neo Smart Bike, Tacx',
    },
    4269: {
      'tacx_satori_smart': 'Satori Smart, Tacx',
    },
    4270: {
      'tacx_flow_smart': 'Flow Smart, Tacx',
    },
    4271: {
      'tacx_vortex_smart': 'Vortex Smart, Tacx',
    },
    4272: {
      'tacx_bushido_smart': 'Bushido Smart, Tacx',
    },
    4273: {
      'tacx_genius_smart': 'Genius Smart, Tacx',
    },
    4274: {
      'tacx_flux_flux_s_smart': 'Flux/Flux S Smart, Tacx',
    },
    4275: {
      'tacx_flux2_smart': 'Flux 2 Smart, Tacx',
    },
    4276: {
      'tacx_magnum': 'Magnum, Tacx',
    },
    4477: {
      'lily_athlete': 'aka the Lily 2 Active',
    },
    4525: {
      'rally_x10': 'Rally 110/210',
    },
    5134: {
      'fenix9': '47mm & 57mm',
    },
    10007: {
      'sdm4': 'SDM4 footpod',
    },
    65534: {
      'connect': 'Garmin Connect website',
    },
  },
  ProfileType.gasConsumptionRateType: {
    0: {
      'pressure_sac': 'Pressure-based Surface Air Consumption',
    },
    1: {
      'volume_sac': 'Volumetric Surface Air Consumption',
    },
    2: {
      'rmv': 'Respiratory Minute Volume',
    },
  },
  ProfileType.goalSource: {
    0: {
      'auto': 'Device generated',
    },
    1: {
      'community': 'Social network sourced goal',
    },
    2: {
      'user': 'Manually generated',
    },
  },
  ProfileType.hipRaiseExerciseName: {
    45: {
      'inner_thigh_circles': 'Deprecated do not use',
    },
    46: {
      'inner_thigh_side_lift': 'Deprecated do not use',
    },
  },
  ProfileType.hyperextensionExerciseName: {
    39: {
      'supine_floor_barre': 'Deprecated do not use',
    },
  },
  ProfileType.leftRightBalance: {
    127: {
      'mask': '% contribution',
    },
    128: {
      'right': 'data corresponds to right if set, otherwise unknown',
    },
  },
  ProfileType.leftRightBalance100: {
    16383: {
      'mask': '% contribution scaled by 100',
    },
    32768: {
      'right': 'data corresponds to right if set, otherwise unknown',
    },
  },
  ProfileType.lengthType: {
    0: {
      'idle': 'Rest period. Length with no strokes',
    },
    1: {
      'active': 'Length with strokes.',
    },
  },
  ProfileType.localDeviceType: {
    0: {
      'gps': 'Onboard gps receiver',
    },
    1: {
      'glonass': 'Onboard glonass receiver',
    },
    2: {
      'gps_glonass': 'Onboard gps glonass receiver',
    },
    3: {
      'accelerometer': 'Onboard sensor',
    },
    4: {
      'barometer': 'Onboard sensor',
    },
    5: {
      'temperature': 'Onboard sensor',
    },
    10: {
      'whr': 'Onboard wrist HR sensor',
    },
    12: {
      'sensor_hub': 'Onboard software package',
    },
  },
  ProfileType.manufacturer: {
    2: {
      'garmin_fr405_antfs': 'Do not use. Used by FR405 for ANTFS man id.',
    },
    96: {
      'icg': 'Indoorcycling Group',
    },
    103: {
      'limits_technology': 'Limits Technology Ltd.',
    },
    104: {
      'topaction_technology': 'TopAction Technology Inc.',
    },
    109: {
      'tigrasport': 'Tigrasport',
    },
    266: {
      'precor': 'Amer Sports',
    },
    269: {
      'navman': 'MiTAC Global Corporation (Mio Technology)',
    },
    270: {
      'cobi': 'COBI GmbH',
    },
    277: {
      'falco_e_motors': 'Falco eMotors Inc.',
    },
    320: {
      'lsec': 'Lishun Electric & Communication',
    },
  },
  ProfileType.maxMetHeartRateSource: {
    0: {
      'whr': 'Wrist Heart Rate Monitor',
    },
    1: {
      'hrm': 'Chest Strap Heart Rate Monitor',
    },
  },
  ProfileType.mesgNum: {
    409: {
      'hsa_wrist_temperature_data':
          'Message number for the HSA wrist temperature data message',
    },
    65280: {
      'mfg_range_min':
          '0xFF00 - 0xFFFE reserved for manufacturer specific messages',
    },
    65534: {
      'mfg_range_max':
          '0xFF00 - 0xFFFE reserved for manufacturer specific messages',
    },
  },
  ProfileType.messageIndex: {
    4095: {
      'mask': 'index',
    },
    28672: {
      'reserved': 'reserved (default 0)',
    },
    32768: {
      'selected': 'message is selected if set',
    },
  },
  ProfileType.noFlyTimeMode: {
    0: {
      'standard': 'Standard Diver Alert Network no-fly guidance',
    },
    1: {
      'flat_24_hours': 'Flat 24 hour no-fly guidance',
    },
  },
  ProfileType.projectileType: {
    0: {
      'arrow': 'Arrow projectile type',
    },
    1: {
      'rifle_cartridge': 'Rifle cartridge projectile type',
    },
    2: {
      'pistol_cartridge': 'Pistol cartridge projectile type',
    },
    3: {
      'shotshell': 'Shotshell projectile type',
    },
    4: {
      'air_rifle_pellet': 'Air rifle pellet projectile type',
    },
    5: {
      'other': 'Other projectile type',
    },
  },
  ProfileType.sensorType: {
    2: {
      'compass': 'Magnetometer',
    },
  },
  ProfileType.sessionTrigger: {
    1: {
      'manual': 'User changed sport.',
    },
    2: {
      'auto_multi_sport':
          'Auto multi-sport feature is enabled and user pressed lap button to advance session.',
    },
    3: {
      'fitness_equipment':
          'Auto sport change caused by user linking to fitness equipment.',
    },
  },
  ProfileType.sourceType: {
    0: {
      'ant': 'External device connected with ANT',
    },
    1: {
      'antplus': 'External device connected with ANT+',
    },
    2: {
      'bluetooth': 'External device connected with BT',
    },
    3: {
      'bluetooth_low_energy': 'External device connected with BLE',
    },
    4: {
      'wifi': 'External device connected with Wifi',
    },
    5: {
      'local': 'Onboard device',
    },
  },
  ProfileType.splitType: {
    17: {
      'rwd_run': 'run/walk detection running',
    },
    18: {
      'rwd_walk': 'run/walk detection walking',
    },
    22: {
      'rwd_stand': 'run/walk detection standing',
    },
    23: {
      'transition':
          'Marks the time going from ascent_split to descent_split/used in backcountry ski',
    },
  },
  ProfileType.sport: {
    3: {
      'transition': 'Mulitsport transition',
    },
    56: {
      'shooting': 'Sport Shooting bits, set here for sport_bits alignment',
    },
    59: {
      'grinding':
          'Sailing position, operating manual winches to power boat controls',
    },
    254: {
      'all': 'All is for goals only to include all sports.',
    },
  },
  ProfileType.sportBits0: {
    8: {
      'transition': 'Mulitsport transition',
    },
  },
  ProfileType.squatExerciseName: {
    87: {
      'kbs_overhead': 'Deprecated do not use',
    },
  },
  ProfileType.strokeType: {
    1: {
      'other': 'stroke was detected but cannot be identified',
    },
  },
  ProfileType.subSport: {
    1: {
      'treadmill': 'Run/Fitness Equipment',
    },
    2: {
      'street': 'Run',
    },
    3: {
      'trail': 'Run',
    },
    4: {
      'track': 'Run',
    },
    5: {
      'spin': 'Cycling',
    },
    6: {
      'indoor_cycling': 'Cycling/Fitness Equipment',
    },
    7: {
      'road': 'Cycling',
    },
    8: {
      'mountain': 'Cycling',
    },
    9: {
      'downhill': 'Cycling',
    },
    10: {
      'recumbent': 'Cycling',
    },
    11: {
      'cyclocross': 'Cycling',
    },
    12: {
      'hand_cycling': 'Cycling',
    },
    13: {
      'track_cycling': 'Cycling',
    },
    14: {
      'indoor_rowing': 'Fitness Equipment',
    },
    15: {
      'elliptical': 'Fitness Equipment',
    },
    16: {
      'stair_climbing': 'Fitness Equipment',
    },
    17: {
      'lap_swimming': 'Swimming',
    },
    18: {
      'open_water': 'Swimming',
    },
    19: {
      'flexibility_training': 'Training',
    },
    20: {
      'strength_training': 'Training',
    },
    21: {
      'warm_up': 'Tennis',
    },
    22: {
      'match': 'Tennis',
    },
    23: {
      'exercise': 'Tennis',
    },
    25: {
      'indoor_skiing': 'Fitness Equipment',
    },
    26: {
      'cardio_training': 'Training',
    },
    27: {
      'indoor_walking': 'Walking/Fitness Equipment',
    },
    28: {
      'e_bike_fitness': 'E-Biking',
    },
    29: {
      'bmx': 'Cycling',
    },
    30: {
      'casual_walking': 'Walking',
    },
    31: {
      'speed_walking': 'Walking',
    },
    32: {
      'bike_to_run_transition': 'Transition',
    },
    33: {
      'run_to_bike_transition': 'Transition',
    },
    34: {
      'swim_to_bike_transition': 'Transition',
    },
    35: {
      'atv': 'Motorcycling',
    },
    36: {
      'motocross': 'Motorcycling',
    },
    37: {
      'backcountry': 'Alpine Skiing/Snowboarding',
    },
    38: {
      'resort': 'Alpine Skiing/Snowboarding',
    },
    39: {
      'rc_drone': 'Flying',
    },
    40: {
      'wingsuit': 'Flying',
    },
    41: {
      'whitewater': 'Kayaking/Rafting',
    },
    42: {
      'skate_skiing': 'Cross Country Skiing',
    },
    43: {
      'yoga': 'Training',
    },
    44: {
      'pilates': 'Fitness Equipment',
    },
    45: {
      'indoor_running': 'Run',
    },
    46: {
      'gravel_cycling': 'Cycling',
    },
    47: {
      'e_bike_mountain': 'Cycling',
    },
    48: {
      'commuting': 'Cycling',
    },
    49: {
      'mixed_surface': 'Cycling',
    },
    53: {
      'single_gas_diving': 'Diving',
    },
    54: {
      'multi_gas_diving': 'Diving',
    },
    55: {
      'gauge_diving': 'Diving',
    },
    56: {
      'apnea_diving': 'Diving',
    },
    57: {
      'apnea_hunting': 'Diving',
    },
    59: {
      'obstacle':
          'Used for events where participants run, crawl through mud, climb over walls, etc.',
    },
    63: {
      'ccr_diving': 'Diving w/ closed circuit rebreather',
    },
    65: {
      'sail_race': 'Sailing',
    },
    66: {
      'expedition': 'Generic',
    },
    67: {
      'ultra': 'Ultramarathon',
    },
    68: {
      'indoor_climbing': 'Climbing',
    },
    69: {
      'bouldering': 'Climbing',
    },
    70: {
      'hiit': 'High Intensity Interval Training',
    },
    71: {
      'indoor_grinding':
          'Sailing position, operating manual winches to power boat controls',
    },
    72: {
      'hunting_with_dogs': 'Hunting',
    },
    73: {
      'amrap': 'HIIT',
    },
    74: {
      'emom': 'HIIT',
    },
    75: {
      'tabata': 'HIIT',
    },
    77: {
      'esport': 'Video Gaming, Cycling, etc.',
    },
    78: {
      'triathlon': 'Multisport',
    },
    79: {
      'duathlon': 'Multisport',
    },
    80: {
      'brick': 'Multisport',
    },
    81: {
      'swim_run': 'Multisport',
    },
    82: {
      'adventure_race': 'Multisport/Running',
    },
    83: {
      'trucker_workout': 'DEZL trucker workout training sport',
    },
    84: {
      'pickleball': 'Racket',
    },
    85: {
      'padel': 'Racket',
    },
    90: {
      'field': 'Hockey',
    },
    91: {
      'ice': 'Hockey',
    },
    92: {
      'ultimate': 'Disc',
    },
    93: {
      'platform': 'Racket',
    },
    94: {
      'squash': 'Racket',
    },
    95: {
      'badminton': 'Racket',
    },
    96: {
      'racquetball': 'Racket',
    },
    97: {
      'table_tennis': 'Racket',
    },
    99: {
      'trolling_motor': 'Generic',
    },
    110: {
      'fly_canopy': 'Flying',
    },
    111: {
      'fly_paraglide': 'Flying',
    },
    112: {
      'fly_paramotor': 'Flying',
    },
    113: {
      'fly_pressurized': 'Flying',
    },
    114: {
      'fly_navigate': 'Flying',
    },
    115: {
      'fly_timer': 'Flying',
    },
    116: {
      'fly_altimeter': 'Flying',
    },
    117: {
      'fly_wx': 'Flying',
    },
    118: {
      'fly_vfr': 'Flying',
    },
    119: {
      'fly_ifr': 'Flying',
    },
    123: {
      'enduro': 'Cycling',
    },
    124: {
      'rucking': 'Hiking',
    },
    125: {
      'rally': 'Motor sports',
    },
    126: {
      'pool_triathlon': 'Multisport',
    },
    127: {
      'e_bike_enduro': 'Cycling',
    },
  },
  ProfileType.swimStroke: {
    6: {
      'im':
          'IM is a mixed interval containing the same number of lengths for each of: Butterfly, Backstroke, Breaststroke, Freestyle, swam in that order.',
    },
    7: {
      'im_by_round':
          'For repeated workout steps, a new individual medly stroke is used for each round.',
    },
    8: {
      'rimo': 'Reverse IM Order',
    },
  },
  ProfileType.timeMode: {
    1: {
      'hour24': 'Does not use a leading zero and has a colon',
    },
    2: {
      'military': 'Uses a leading zero and does not have a colon',
    },
  },
  ProfileType.tissueModelType: {
    0: {
      'zhl_16c': 'Buhlmann\'s decompression algorithm, version C',
    },
  },
  ProfileType.warmUpExerciseName: {
    16: {
      'scorpion': 'Deprecated do not use',
    },
    74: {
      'ninety_ninety_hip_switch': '90_90_hip_switch',
    },
  },
  ProfileType.weatherReport: {
    1: {
      'forecast': 'Deprecated use hourly_forecast instead',
    },
  },
  ProfileType.workoutCapabilities: {
    32: {
      'tcx':
          'For backwards compatibility. Watch should add missing id fields then clear flag.',
    },
    128: {
      'speed': 'Speed source required for workout step.',
    },
    256: {
      'heart_rate': 'Heart rate source required for workout step.',
    },
    512: {
      'distance': 'Distance source required for workout step.',
    },
    1024: {
      'cadence': 'Cadence source required for workout step.',
    },
    2048: {
      'power': 'Power source required for workout step.',
    },
    4096: {
      'grade': 'Grade source required for workout step.',
    },
    8192: {
      'resistance': 'Resistance source required for workout step.',
    },
  },
};
