// Auto-generated by tool/generate_profile.dart. Do not edit by hand.
//
// Every FIT message type available in this profile version.

import '../types/mesg_num.dart';

/// Every FIT message type available in this profile version.
///
/// Each value carries the message names and its global [MesgNum], so callers
/// can enumerate or filter the FIT message types at runtime.
enum MesgType {
  fileId('FileId', 'file_id', MesgNum.fileId),
  capabilities('Capabilities', 'capabilities', MesgNum.capabilities),
  deviceSettings('DeviceSettings', 'device_settings', MesgNum.deviceSettings),
  userProfile('UserProfile', 'user_profile', MesgNum.userProfile),
  hrmProfile('HrmProfile', 'hrm_profile', MesgNum.hrmProfile),
  sdmProfile('SdmProfile', 'sdm_profile', MesgNum.sdmProfile),
  bikeProfile('BikeProfile', 'bike_profile', MesgNum.bikeProfile),
  zonesTarget('ZonesTarget', 'zones_target', MesgNum.zonesTarget),
  hrZone('HrZone', 'hr_zone', MesgNum.hrZone),
  powerZone('PowerZone', 'power_zone', MesgNum.powerZone),
  metZone('MetZone', 'met_zone', MesgNum.metZone),
  sport('Sport', 'sport', MesgNum.sport),
  trainingSettings(
      'TrainingSettings', 'training_settings', MesgNum.trainingSettings),
  goal('Goal', 'goal', MesgNum.goal),
  session('Session', 'session', MesgNum.session),
  lap('Lap', 'lap', MesgNum.lap),
  record('Record', 'record', MesgNum.record),
  event('Event', 'event', MesgNum.event),
  deviceInfo('DeviceInfo', 'device_info', MesgNum.deviceInfo),
  workout('Workout', 'workout', MesgNum.workout),
  workoutStep('WorkoutStep', 'workout_step', MesgNum.workoutStep),
  schedule('Schedule', 'schedule', MesgNum.schedule),
  weightScale('WeightScale', 'weight_scale', MesgNum.weightScale),
  course('Course', 'course', MesgNum.course),
  coursePoint('CoursePoint', 'course_point', MesgNum.coursePoint),
  totals('Totals', 'totals', MesgNum.totals),
  activity('Activity', 'activity', MesgNum.activity),
  software('Software', 'software', MesgNum.software),
  fileCapabilities(
      'FileCapabilities', 'file_capabilities', MesgNum.fileCapabilities),
  mesgCapabilities(
      'MesgCapabilities', 'mesg_capabilities', MesgNum.mesgCapabilities),
  fieldCapabilities(
      'FieldCapabilities', 'field_capabilities', MesgNum.fieldCapabilities),
  fileCreator('FileCreator', 'file_creator', MesgNum.fileCreator),
  bloodPressure('BloodPressure', 'blood_pressure', MesgNum.bloodPressure),
  speedZone('SpeedZone', 'speed_zone', MesgNum.speedZone),
  monitoring('Monitoring', 'monitoring', MesgNum.monitoring),
  trainingFile('TrainingFile', 'training_file', MesgNum.trainingFile),
  hrv('Hrv', 'hrv', MesgNum.hrv),
  antRx('AntRx', 'ant_rx', MesgNum.antRx),
  antTx('AntTx', 'ant_tx', MesgNum.antTx),
  antChannelId('AntChannelId', 'ant_channel_id', MesgNum.antChannelId),
  length('Length', 'length', MesgNum.length),
  monitoringInfo('MonitoringInfo', 'monitoring_info', MesgNum.monitoringInfo),
  pad('Pad', 'pad', MesgNum.pad),
  slaveDevice('SlaveDevice', 'slave_device', MesgNum.slaveDevice),
  connectivity('Connectivity', 'connectivity', MesgNum.connectivity),
  weatherConditions(
      'WeatherConditions', 'weather_conditions', MesgNum.weatherConditions),
  weatherAlert('WeatherAlert', 'weather_alert', MesgNum.weatherAlert),
  cadenceZone('CadenceZone', 'cadence_zone', MesgNum.cadenceZone),
  hr('Hr', 'hr', MesgNum.hr),
  segmentLap('SegmentLap', 'segment_lap', MesgNum.segmentLap),
  memoGlob('MemoGlob', 'memo_glob', MesgNum.memoGlob),
  segmentId('SegmentId', 'segment_id', MesgNum.segmentId),
  segmentLeaderboardEntry('SegmentLeaderboardEntry',
      'segment_leaderboard_entry', MesgNum.segmentLeaderboardEntry),
  segmentPoint('SegmentPoint', 'segment_point', MesgNum.segmentPoint),
  segmentFile('SegmentFile', 'segment_file', MesgNum.segmentFile),
  workoutSession('WorkoutSession', 'workout_session', MesgNum.workoutSession),
  watchfaceSettings(
      'WatchfaceSettings', 'watchface_settings', MesgNum.watchfaceSettings),
  gpsMetadata('GpsMetadata', 'gps_metadata', MesgNum.gpsMetadata),
  cameraEvent('CameraEvent', 'camera_event', MesgNum.cameraEvent),
  timestampCorrelation('TimestampCorrelation', 'timestamp_correlation',
      MesgNum.timestampCorrelation),
  gyroscopeData('GyroscopeData', 'gyroscope_data', MesgNum.gyroscopeData),
  accelerometerData(
      'AccelerometerData', 'accelerometer_data', MesgNum.accelerometerData),
  threeDSensorCalibration('ThreeDSensorCalibration',
      'three_d_sensor_calibration', MesgNum.threeDSensorCalibration),
  videoFrame('VideoFrame', 'video_frame', MesgNum.videoFrame),
  obdiiData('ObdiiData', 'obdii_data', MesgNum.obdiiData),
  nmeaSentence('NmeaSentence', 'nmea_sentence', MesgNum.nmeaSentence),
  aviationAttitude(
      'AviationAttitude', 'aviation_attitude', MesgNum.aviationAttitude),
  video('Video', 'video', MesgNum.video),
  videoTitle('VideoTitle', 'video_title', MesgNum.videoTitle),
  videoDescription(
      'VideoDescription', 'video_description', MesgNum.videoDescription),
  videoClip('VideoClip', 'video_clip', MesgNum.videoClip),
  ohrSettings('OhrSettings', 'ohr_settings', MesgNum.ohrSettings),
  exdScreenConfiguration('ExdScreenConfiguration', 'exd_screen_configuration',
      MesgNum.exdScreenConfiguration),
  exdDataFieldConfiguration('ExdDataFieldConfiguration',
      'exd_data_field_configuration', MesgNum.exdDataFieldConfiguration),
  exdDataConceptConfiguration('ExdDataConceptConfiguration',
      'exd_data_concept_configuration', MesgNum.exdDataConceptConfiguration),
  fieldDescription(
      'FieldDescription', 'field_description', MesgNum.fieldDescription),
  developerDataId(
      'DeveloperDataId', 'developer_data_id', MesgNum.developerDataId),
  magnetometerData(
      'MagnetometerData', 'magnetometer_data', MesgNum.magnetometerData),
  barometerData('BarometerData', 'barometer_data', MesgNum.barometerData),
  oneDSensorCalibration('OneDSensorCalibration', 'one_d_sensor_calibration',
      MesgNum.oneDSensorCalibration),
  monitoringHrData(
      'MonitoringHrData', 'monitoring_hr_data', MesgNum.monitoringHrData),
  timeInZone('TimeInZone', 'time_in_zone', MesgNum.timeInZone),
  set_('Set', 'set', MesgNum.set_),
  stressLevel('StressLevel', 'stress_level', MesgNum.stressLevel),
  maxMetData('MaxMetData', 'max_met_data', MesgNum.maxMetData),
  diveSettings('DiveSettings', 'dive_settings', MesgNum.diveSettings),
  diveGas('DiveGas', 'dive_gas', MesgNum.diveGas),
  diveAlarm('DiveAlarm', 'dive_alarm', MesgNum.diveAlarm),
  exerciseTitle('ExerciseTitle', 'exercise_title', MesgNum.exerciseTitle),
  diveSummary('DiveSummary', 'dive_summary', MesgNum.diveSummary),
  spo2Data('Spo2Data', 'spo2_data', MesgNum.spo2Data),
  sleepLevel('SleepLevel', 'sleep_level', MesgNum.sleepLevel),
  jump('Jump', 'jump', MesgNum.jump),
  aadAccelFeatures(
      'AadAccelFeatures', 'aad_accel_features', MesgNum.aadAccelFeatures),
  beatIntervals('BeatIntervals', 'beat_intervals', MesgNum.beatIntervals),
  respirationRate(
      'RespirationRate', 'respiration_rate', MesgNum.respirationRate),
  hsaAccelerometerData('HsaAccelerometerData', 'hsa_accelerometer_data',
      MesgNum.hsaAccelerometerData),
  hsaStepData('HsaStepData', 'hsa_step_data', MesgNum.hsaStepData),
  hsaSpo2Data('HsaSpo2Data', 'hsa_spo2_data', MesgNum.hsaSpo2Data),
  hsaStressData('HsaStressData', 'hsa_stress_data', MesgNum.hsaStressData),
  hsaRespirationData(
      'HsaRespirationData', 'hsa_respiration_data', MesgNum.hsaRespirationData),
  hsaHeartRateData(
      'HsaHeartRateData', 'hsa_heart_rate_data', MesgNum.hsaHeartRateData),
  split('Split', 'split', MesgNum.split),
  splitSummary('SplitSummary', 'split_summary', MesgNum.splitSummary),
  hsaBodyBatteryData('HsaBodyBatteryData', 'hsa_body_battery_data',
      MesgNum.hsaBodyBatteryData),
  hsaEvent('HsaEvent', 'hsa_event', MesgNum.hsaEvent),
  climbPro('ClimbPro', 'climb_pro', MesgNum.climbPro),
  tankUpdate('TankUpdate', 'tank_update', MesgNum.tankUpdate),
  tankSummary('TankSummary', 'tank_summary', MesgNum.tankSummary),
  sleepAssessment(
      'SleepAssessment', 'sleep_assessment', MesgNum.sleepAssessment),
  hrvStatusSummary(
      'HrvStatusSummary', 'hrv_status_summary', MesgNum.hrvStatusSummary),
  hrvValue('HrvValue', 'hrv_value', MesgNum.hrvValue),
  rawBbi('RawBbi', 'raw_bbi', MesgNum.rawBbi),
  deviceAuxBatteryInfo('DeviceAuxBatteryInfo', 'device_aux_battery_info',
      MesgNum.deviceAuxBatteryInfo),
  hsaGyroscopeData(
      'HsaGyroscopeData', 'hsa_gyroscope_data', MesgNum.hsaGyroscopeData),
  chronoShotSession(
      'ChronoShotSession', 'chrono_shot_session', MesgNum.chronoShotSession),
  chronoShotData('ChronoShotData', 'chrono_shot_data', MesgNum.chronoShotData),
  hsaConfigurationData('HsaConfigurationData', 'hsa_configuration_data',
      MesgNum.hsaConfigurationData),
  diveApneaAlarm('DiveApneaAlarm', 'dive_apnea_alarm', MesgNum.diveApneaAlarm),
  skinTempOvernight(
      'SkinTempOvernight', 'skin_temp_overnight', MesgNum.skinTempOvernight),
  hsaWristTemperatureData('HsaWristTemperatureData',
      'hsa_wrist_temperature_data', MesgNum.hsaWristTemperatureData),
  napEvent('NapEvent', 'nap_event', MesgNum.napEvent),
  sleepDisruptionSeverityPeriod(
      'SleepDisruptionSeverityPeriod',
      'sleep_disruption_severity_period',
      MesgNum.sleepDisruptionSeverityPeriod),
  sleepDisruptionOvernightSeverity(
      'SleepDisruptionOvernightSeverity',
      'sleep_disruption_overnight_severity',
      MesgNum.sleepDisruptionOvernightSeverity),
  ;

  const MesgType(this.pascalName, this.snakeName, this.num);

  /// PascalCase name, matching `Mesg.name` on a decoded message.
  final String pascalName;

  /// snake_case name, matching the generated Dart file names.
  final String snakeName;

  /// Global message number (a [MesgNum] constant).
  final int num;

  static final Map<String, MesgType> _byPascalName = {
    for (final t in values) t.pascalName: t,
  };
  static final Map<String, MesgType> _bySnakeName = {
    for (final t in values) t.snakeName: t,
  };
  static final Map<int, MesgType> _byNum = {
    for (final t in values) t.num: t,
  };

  /// The message type whose [pascalName] equals [name], or null.
  static MesgType? byPascalName(String name) => _byPascalName[name];

  /// The message type whose [snakeName] equals [name], or null.
  static MesgType? bySnakeName(String name) => _bySnakeName[name];

  /// The message type whose [num] equals [num], or null.
  static MesgType? byNum(int num) => _byNum[num];
}
