#!/usr/bin/env bash
#
# Additively updates this package to Garmin's latest FIT profile.
#
#   tool/update_profile.sh           # update the working tree + report
#   tool/update_profile.sh --pr      # also branch, commit, push and open a PR
#
# It downloads the Garmin FIT JavaScript SDK's profile.js, runs the additive
# generator, formats only the touched files, and checks that the package still
# compiles. Safe to run repeatedly: when nothing is new, it makes no changes.

set -euo pipefail
cd "$(dirname "$0")/.."

PROFILE_URL="https://raw.githubusercontent.com/garmin/fit-javascript-sdk/main/src/profile.js"
DART="dart"
command -v fvm >/dev/null 2>&1 && DART="fvm dart"

say() { printf '\033[1m%s\033[0m\n' "$*"; }

tmp_profile="$(mktemp)"
trap 'rm -f "$tmp_profile"' EXIT
say "↓ Downloading Garmin profile.js…"
curl -fsSL -o "$tmp_profile" "$PROFILE_URL"

version="$(grep -m1 -A3 'version:' "$tmp_profile" \
  | grep -oE 'major: [0-9]+|minor: [0-9]+|patch: [0-9]+' \
  | grep -oE '[0-9]+' | paste -sd. -)"
say "  profile version: ${version}"

say "⚙  Running additive generator…"
# The generator prints the files that need formatting to stdout.
to_format="$($DART run tool/generate_profile.dart "$tmp_profile")"
if [ -n "${to_format// }" ]; then
  # shellcheck disable=SC2086
  $DART format $to_format >/dev/null
fi

# Detect any change, including brand-new (untracked) type/message files.
if [ -z "$(git status --porcelain -- lib)" ]; then
  say "✓ Already up to date (no changes)."
  exit 0
fi

# Record the profile version; the CI tag workflow reads this on merge to main.
echo "$version" > FIT_PROFILE_VERSION

say "🔎 Verifying the package still compiles…"
$DART analyze lib >/dev/null

say "📋 $(git status --porcelain -- lib | wc -l | tr -d ' ') file(s) changed:"
git --no-pager status --short -- lib | sed 's/^/   /'

if [ "${1:-}" != "--pr" ]; then
  say "Done. Review the working tree, or re-run with --pr to open a pull request."
  exit 0
fi

branch="auto/profile-${version}"
if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
  say "↪ ${branch} already exists on origin — a PR is likely already open. Skipping."
  exit 0
fi
say "🌿 Opening PR on branch ${branch}…"
git switch -c "$branch"
git add -A lib FIT_PROFILE_VERSION
git commit -q -m "feat: additively update FIT profile to v${version}

Generated by tool/update_profile.sh from Garmin's official FIT SDK profile.
Profile data © Garmin under the FIT Protocol License."
git push -u origin "$branch"
gh pr create --fill --base main --head "$branch" 2>/dev/null \
  || say "Pushed ${branch}; open the PR manually if gh is unavailable."
say "✓ Done."
